"""initial_schema_with_ai_agent_log

Revision ID: d4ffd786cee1
Revises: 
Create Date: 2026-03-26 22:49:06.749400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ffd786cee1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('action_taken', sa.String(length=200), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('agent_metadata', sa.Text(), nullable=True),
    sa.Column('human_reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_agent_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_agent_logs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_agent_logs_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('ai_disclaimer_appended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('reports')
    op.drop_table('posts')
    op.drop_table('notifications')
    with op.batch_alter_table('ai_agent_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_agent_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_agent_logs_agent_name'))

    op.drop_table('ai_agent_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
